server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpectraPhantom/courseapp-config-repo
          search-paths: userservice,courseservice,zuulserver,authorizationserver,eurekaserver
        encrypt:
          enabled: false